name: Kyuri Jo
author: Kyuri Jo
url: http://kyurijo.github.io
baseurl: /
description: Computational biologist
github: http://github.com/kyuriJo
linkedin: http://www.linkedin.com/in/kyuriJo-bioinfo
email: mailto:kyurijo@chungbuk.ac.kr

##Make sure to edit the above fields, especially for disqus.

plugins:
 - jekyll-seo-tag

highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
