name: Kyuri Jo
author: Kyuri Jo
baseurl: /
description: Personal webpage of Kyuri Jo
github: http://github.com/kyuriJo
twitter: http://twitter.com/kyuri_jo
linkedin: http://www.linkedin.com/in/kyuriJo-bioinfo
email: keialk[at]snu.ac.kr

##Make sure to edit the above fields, especially for disqus.

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
